SELECT lkVárosKerületenkéntiFõosztályonkéntiLétszám04.*, lkFõosztályonkéntiBetöltöttLétszám.FõosztályiLétszám AS Összesen
FROM lkFõosztályonkéntiBetöltöttLétszám INNER JOIN lkVárosKerületenkéntiFõosztályonkéntiLétszám04 ON lkFõosztályonkéntiBetöltöttLétszám.Fõosztály=lkVárosKerületenkéntiFõosztályonkéntiLétszám04.Fõosztály;
