SELECT tEllenõrzõLekérdezések.azEllenõrzõ, tEllenõrzõLekérdezések.EllenõrzõLekérdezés, tEllenõrzõLekérdezések.azETípus, tLekérdezésTípusok.TípusNeve, tEllenõrzõLekérdezések.Kimenet
FROM tLekérdezésTípusok INNER JOIN tEllenõrzõLekérdezések ON tLekérdezésTípusok.azETípus = tEllenõrzõLekérdezések.azETípus;
