SELECT lkLekérdezésekMezõinekSzáma.EllenõrzõLekérdezés, lkLekérdezésekMezõinekSzáma.CountOfAttribute, lkEllenõrzõLekérdezésekTípusolMezõinekSzáma.CountOfMezõNeve, lkEllenõrzõLekérdezésekTípusolMezõinekSzáma.EllenõrzõLekérdezés
FROM lkLekérdezésekMezõinekSzáma RIGHT JOIN lkEllenõrzõLekérdezésekTípusolMezõinekSzáma ON lkLekérdezésekMezõinekSzáma.EllenõrzõLekérdezés = lkEllenõrzõLekérdezésekTípusolMezõinekSzáma.EllenõrzõLekérdezés
WHERE (((lkEllenõrzõLekérdezésekTípusolMezõinekSzáma.CountOfMezõNeve)<[CountOfAttribute]));
