SELECT lkSzemélyek.[TAJ szám] AS [azonosító száma],
  "" AS [név előtag], 
  lkSzemélyek.[Dolgozó teljes neve] AS [munkavállaló neve],
  lkSzemélyek.Neme AS nem, lkSzemélyek.[Születési hely], 
  lkSzemélyek.[Születési idő], 
  lkSzemélyek.[Dolgozó születési neve] AS [leánykori név], 
  lkSzemélyek.[Anyja neve], 
  lkSzemélyek.[Hivatali telefon] AS [telefon szám], 
  lkSzemélyek.[Hivatali email] AS [e-mail], 
  lkSzemélyek.[Állandó lakcím] AS lakcím, 
  "" AS jogosítvány, 
  "" AS [katonai szolgálat], Trim(ffsplit([FEOR],"-",1)) AS [FEOR kód], 
  Trim(ffsplit([FEOR],"-",2)) AS [FEOR név], 
  "" AS [foglalkozásegészségügyi osztály], 
  "" AS [fizikai megterhelés], 
  "Budapest Főváros Kormányhivatala" AS [cég teljes neve], 
  "BFKH" AS [cég rövid neve], 
  lkSzemélyek.[Munkavégzés helye - megnevezés] AS [telephely neve], 
  lkSzemélyek.[Munkavégzés helye - cím] AS [telephely címe], 
  lkSzemélyek.[Jogviszony kezdete (belépés dátuma)] AS [munkaviszony kezdete], 
  lkSzemélyek.[Orvosi vizsgálat időpontja] AS [alkalmassági vizsgálat dátuma], 
  lkSzemélyek.[Orvosi vizsgálat következő időpontja] AS [alkalmassági vizsgálat érvényesség], 
  lkSzemélyek.[Orvosi vizsgálat típusa] AS [alkalmassági vizsgálat típus], 
  lkSzemélyek.[Orvosi vizsgálat eredménye] AS [alkalmassági vizsgálat eredmény], 
  lkSzemélyek.[Orvosi vizsgálat észrevételek] AS [alkalmassági vizsgálat korlázotás]
FROM lkSzemélyek
WHERE (((lkSzemélyek.[Státusz neve])="Álláshely"));
